### ISSUE TITLE
Find a CSS framework other than bootstrap

### ISSUE THREAD

**Issue by miitodev** [IanHooper613/Project-1#3]
We need to find a CSS framework that suits our needs.

**Comment by mscoulte** [comment]
Heres a couple of options I put together quickly:

Bulma : [docs](https://bulma.io/documentation/)
Semantic UI: [docs](https://semantic-ui.com/)
Tailwind CSS: [docs](https://tailwindcss.com/docs/installation)
Foundation : [docs](https://get.foundation/sites/docs/)
Ulkit: [docs](https://getuikit.com/docs/introduction)

**Comment by miitodev** [comment]
Semantic UI hasn't been updated since 2018.
I found this update to date fork version of Sermantic call [Fomantic UI](https://github.com/fomantic/fomantic-ui/)

**Comment by miitodev** [comment]
Blaze UI: [docs](https://www.blazeui.com/)

**Comment by miitodev** [comment]
This projects will use the Bulma CSS framework as discuss.
