### ISSUE TITLE
No alerts and prompts, try Modals

### ISSUE THREAD

**Issue by IanHooper613** [IanHooper613/Project-1#5]
Modals Boxes w/ JS (https://medium.com/@nerdplusdog/a-how-to-guide-for-modal-boxes-with-javascript-html-and-css-6a49d063987e)

**Comment by mscoulte** [comment]
Basic Modal Tutorials- 
[w3schools](https://www.w3schools.com/howto/howto_css_modals.asp)
https://webdesign.tutsplus.com/tutorials/how-to-build-flexible-modal-dialogs-with-html-css-and-javascript--cms-33500

**Comment by miitodev** [comment]
Modals are include with Bulma CSS framework.
